### ISSUE TITLE
Loader is used without the corresponding plugin error

### ISSUE THREAD

**Issue by benregan** [webpack/extract-text-webpack-plugin#173]
I sure could use some help... I implemented extracttext plugin so that I could take advantage of scss sourcemaps for debugging front end styles in my app, however when I run any of my tests it is failing at my 1st .scss include with that same message ( pasted below ). I did get scss source maps working finally, but now I can't get past my build because of this error. Any help would be greatly appreciated, I've been banging my head on this for days. ( I found a similar issue thread [here](https://github.com/ampedandwired/html-webpack-plugin/pull/201), but I am very unfamiliar with webpack so far and not really sure how to begin troubleshooting. )

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

below is my exports.
```
module.exports = {

    cache: true,

    entry: {
        app: appEntryPoints
    },

    output: {
        path: path.join(__dirname, 'www'),
        filename: '[name].js',
        chunkFilename: '[chunkhash].js'
    },

    devtool: 'source-map',

    devServer: {
        contentBase: 'www/',
        port: 8100
    },

    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                include: [
                    path.resolve(__dirname, 'src'),
                    /ionic-framework[\/\\]index\.js/i,
                    /angular-ios9-patch/i
                ],
                exclude: es5Patterns
            },
            {
                test: /\.css$/,
                loader: 'style!css'
            },
            {
                test: /\.html$/,
                loader: 'raw'
            },
            {
                test: /\.json$/,
                loader: 'json'
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract('style-loader',
                    'css-loader?sourceMap!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true')
            },
            {
                test: /\.(ttf|otf|eot|svg|woff2?)(\?.+)?$/,
                loader: 'url',
                query: {
                    limit: 10000
                }
            },
            {
                //IMAGE LOADER
                test: /\.(jpe?g|png|gif|svg)$/i,
                loader: 'file'
            },
        ],
        noParse: es5Patterns
    },

    plugins: [
        new webpack.DefinePlugin({
            APP_ENV: JSON.stringify(appEnvironment),
            BUILD_TARGET: JSON.stringify(target)
        }),
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            BUILD_TARGET: target
        }),
        new ExtractTextPlugin("style.css", {
            allChunks: true
        })
    ]

};
```

**Comment by kevinSuttle** [comment]
This just started happening out of nowhere with me, too. I didn't add any new modules. Not sure what changed, to be honest.
```js
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var BrowserSyncPlugin = require('browser-sync-webpack-plugin');

module.exports = {
  entry: './index.js',
  output: {
    filename: './build/bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.js?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel',
        query: {
          presets: ['react', 'es2015']
        },
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("style-loader", "css-loader?modules")
      },
      {
        test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'
      },
    ],
    resolve: {
      extensions: ['', '.js', '.json', '.css']
    },
    plugins: [
      new ExtractTextPlugin('TextInputs/TextInputs.css', { allChunks: true } ),
      new BrowserSyncPlugin({
        host: 'localhost',
        port: 3000,
        server: { baseDir: ['.'] },
        reload: false
      })
    ],
  }
}
```

**Comment by kevinSuttle** [comment]
Happens anytime I'm trying to import a CSS file in my JS module.

Either `var css = require("css!./TextInputs.css");` or `import styles from './TextInputs.css';` causes this error. 

Commenting that line out causes Webpack to run, but the server to not kick off, even with `webpack --watch`.

**Comment by floross** [comment]
I got the same issue since I updated my node version to `6.0.0`. When I fallback to an earlier version (like `5.x.x` or `4.x.x`), my code works as expected.

**Comment by kevinSuttle** [comment]
@floross Ohhhh. I didn't even think of that.

**Comment by facejiong** [comment]
I got the same issue with you @floross

**Comment by max-mykhailenko** [comment]
Have this problem with node 6.0.0, with 5.4.1 works fine

**Comment by fiture** [comment]
I got the same issue in node v6.1.0~

**Comment by agileago** [comment]
me too at node v6.1.0

**Comment by pandada8** [comment]
@max-mykhailenko 
@agileago 
@fiture 
@kevinSuttle 
@floross 
@facejiong 
Hey, are you using something like `npminstall`, `pnpm` or `ied` with node6 ? it seems #186 is the related bug.

**Comment by max-mykhailenko** [comment]
@pandada8 I use simple `npm install` command

**Comment by pandada8** [comment]
@max-mykhailenko interesting, in my test, the original `npm install` works well, at least with the simplest test.

**Comment by max-mykhailenko** [comment]
@pandada8  npm install works good, but webpack build fails.

**Comment by pandada8** [comment]
node changed the way handling symlinked modules in the node 6.0.0, and reverted default behaviour in 6.2.
if you have:
1. node >= 6.0 and <= 6.1
2. install the modules using npm alternatives (ied, npminstall, pnpm)
3. or having symlinked extract-text-webpack-plugin (should not happened in the normal npm install case)
4. and your webpack build is failing

try upgrading your node to **6.2**
for detail see https://github.com/webpack/extract-text-webpack-plugin/issues/186#issuecomment-220319256

**Comment by evilebottnawi** [comment]
@pandada8 i have node `6.2` and got this error.

**Comment by jiyinyiyong** [comment]
6.2 works for me.
```text
=>> uname -a
Darwin chen 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

**Comment by pandada8** [comment]
@evilebottnawi @max-mykhailenko  would you mind providing some examples of your configs?

**Comment by evilebottnawi** [comment]
@pandada8 
```js
{
loader: ExtractTextPlugin.extract([
     'style-loader',
    `css-loader?${JSON.stringify({
        sourceMap: DEBUG,
        // CSS Modules https://github.com/css-modules/css-modules
        // modules: true,
        // localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
        // CSS Nano http://cssnano.co/options/
        minimize: false,
        camelCase: true,
        url: false,
        'import': false
    })}`,
    'postcss-loader',
    `sass-loader?${JSON.stringify({
        sourceMap: DEBUG,
        config: 'sassConfig'
    })}`
])
}
```

**Comment by pandada8** [comment]
@evilebottnawi I think ExtractTextPlugin.extract only receive two parameters, maybe you should just use an array to wrap your css loaders ?

**Comment by noyobo** [comment]
I got the same issue in node v6.1.0

upgrade to v6.2.0  it works

**Comment by benregan** [comment]
I believe this has been resolved!!  Thanks for all the help and comments!

**Comment by monokrome** [comment]
I'm getting this on node 6.2.1. Is it possible that the issue has returned?

**Comment by eilijah69** [comment]
Same problem here with 6.2.2, tried with npminstall and pnpn with no success. 
```
var cssLoadersDev = ExtractTextPlugin.extract(
    'style-loader',
    'css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader'
)
```

**Comment by robhadfield** [comment]
Yep - 6.2.2 still happening for me. Any resolution?

**Comment by ibufu** [comment]
node v6.2.2, fail

**Comment by ibufu** [comment]
I found an reason caused by happypack.

**Comment by leocaseiro** [comment]
Same here with node v6.3.0, I've tried node 6.3.1, 6.2.0. 5.0.0 and 4.4.5 and none worked.

**Comment by ephor** [comment]
I agree with @ibufu. I want to speed up the stylus build with happypack, but got this error. Node v 6.4.0

**Comment by monokrome** [comment]
I don't think that I was using happypack

**Comment by Prairie-Falcon** [comment]
Node v6.2.0. No happypack anywhere.

webpack.config.js:
...
let ExtractTextPlugin = require("extract-text-webpack-plugin")
...
entry: [
    "./app/example.css",
    ...
]
...
module: {
    loaders: [
        {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract("style-loader", "css-loader")
        },
        ....
    ],
    plugins: [
        new ExtractTextPlugin("styles.css")
    ],
    ...
}

index.html:
    <html>
    <head>
    ...
    <link href="./ProgramJS.css" rel="stylesheet" type="text/css" />
    ...
    </head>
    ...
    </html>

example.js:
    ...
    require("./ProgramJS.css") // grasping at straws, doesn't seem right
    ...

result:
ERROR in ./app/example.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\path\to\local\node_modules\extract-text-webpack-plugin\loader.js:21:9)
 @ multi main

**Comment by Prairie-Falcon** [comment]
Issue 24 is closed because of 50.

Issue 50 is closed because of 24.

Issue 73 is closed because it was marked a "question". It suggests the problem might be location of `node_modules`: don't use `/Users/${userName}/node_modules`. For my case, I'm not.

Issue 173 (this one) suggests the problem may be interaction with `happypath`. For my case, I don't have it on my system. I'm not aware of ever having had it.

There's suggestion to downgrade Node to before 6.0.0.

Any chance of another option? Workaround?

**Comment by Prairie-Falcon** [comment]
New report; I hope this helps someone.

This condition remains for me; I cannot use extract-text-webpack-plugin.

On the other hand, the urgency has gone way down for me. I substituted the following configuration:

webpack.config.js:
...
// let ExtractTextPlugin = require("extract-text-webpack-plugin")
...
entry: [
"./app/example.css",
...
]
...
module: {
loaders: [
{
test: /.css$/,
loader: "style-loader!css-loader"
},
....
],
// plugins: [
// new ExtractTextPlugin("styles.css")
// ],
...
}

index.html: (no change from above)

example.js:
...
// require("./ProgramJS.css") // caused syntax errors
...

Initially, I got an error message that I didn't document. I don't know what else I did, or otherwise why it suddenly started working, but it's working. This is a viable workaround for me and for now.

**Comment by kl2karpenko** [comment]
I had this problem because I din't have less or scss file included in=n my scripts, think this causes an error because it can't find a file to test

**Comment by csawtelle** [comment]
This happened for me whenever I was using styleUrl: something.css with angular2

**Comment by ejosafat** [comment]
I have this issue as well, using node 6.3. Tried with node 7.1 and the problem persists. This is my config:

```javascript
const buildFilelist = require('./buildFilelist').buildFilelist;
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

let config = {
    entry: buildFilelist(),
    output: {
        path: __dirname + '/assets/public/compiled',
        filename: '[name].js',
    },
    resolve: {
        extensions: ['', '.js', '.es6', '.json'],
        root: [
            path.resolve('./assets/public/responsive/tutorial'),
            path.resolve('./assets/public/responsive/tracking'),
            path.resolve('./assets/public/responsive/dataProviders'),
            path.resolve('./assets/public/responsive/templateStyles'),
            path.resolve('./assets/public/responsive/panels/CustomDisplayPanel'),
            path.resolve('./assets/public/responsive/panels/AppSwitcher'),
            path.resolve('./assets/public/responsive/panels/PagesPanel'),
            path.resolve('./assets/public/responsive/panels/FilesPanel'),
            path.resolve('./assets/public/responsive/panels/SidebarPanel'),
            path.resolve('./assets/public/responsive/panels/NotificationCenter'),
            path.resolve('./assets/public/responsive/panels/HelpCenter'),
            path.resolve('./assets/public/responsive/settings/WidgetPanel'),
            path.resolve('./assets/public/responsive/settings'),
            path.resolve('./assets/public/responsive/panels/Toolbar'),
            path.resolve('./assets/public/responsive/panels/PublishPanel'),
            path.resolve('./assets/public/responsive/panels/HiddenWidgetsPanel'),
            path.resolve('./assets/public/responsive/utils'),
            path.resolve('./assets/public/responsive/error'),
            path.resolve('./assets/public/responsive/dragdrop'),
            path.resolve('./assets/public/responsive/editor-v8'),
            path.resolve('./assets/public/responsive/widgetServices'),
            path.resolve('./assets/public/responsive/globals'),
            path.resolve('./assets/public/responsive/globals/Widgets'),
            path.resolve('./assets/public/responsive'),
            path.resolve('./assets/public/apps/js/framework/modules'),
            path.resolve('./assets/public/responsive/widgetactions'),
            path.resolve('./plugins/blog/resources/public/js/v8'),
        ],
    },
    resolveLoader: {
        modulesDirectories: ["bk_loaders", "web_loaders", "web_modules", "node_loaders", "node_modules"],
    },
    module: {
        loaders: [
            {
                test: /node_modules/,
                loader: 'imports-loader'
            },
            {
                test: /\.js$/,
                loader: 'bk-js-loader',
                exclude: /node_modules/
            },
            {
                test: /\.jsx$/,
                loader: 'babel',
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'sass-loader'),
            },
        ]
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                 warnings: false
            }
        }),
        new ExtractTextPlugin('[name].css', { allChunks: true }),
    ]
};

module.exports = config;
```

**Comment by edap** [comment]
This is still happening. This is my actual configuration

```pre
var ExtractTextPlugin = require('extract-text-webpack-plugin');
...
      {
          test: /\.scss$/i, loader: ExtractTextPlugin.extract('css!sass')
      },
```

**Comment by Measy** [comment]
@pandada8  it seems node v6.9.0 still has the problem, do i need to return back old version? as follows
`var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
    entry: {
        index: "./src/js/page/index.js"
    },
    output: {
        path: path.join(__dirname, 'dist'),
        publicPath: "/dist/",
        filename: "js/[name].js",
        chunkFilename: "js/[id].chunk.js"
    },
    module:{
        loaders: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            }
        ]
    },
    plugin: [
        new ExtractTextPlugin("css/[name].css",), 
        new HtmlWebpackPlugin({
            favicon: './src/img/favicon.ico', 
            filename: '/view/index.html', 
            template: './src/view/index.html', 
            inject: true,
            hash: true, 
            minify: { 
                removeComments: true, 
                collapseWhitespace: false 
            }
        })
    ]
}`

**Comment by Measy** [comment]
@Prairie-Falcon  does this has been resolved? i have the same question

**Comment by jboothe** [comment]
I resolved this with the addition of `include` in the rules test object. Hope this helps someone. 

```
rules: [
       // . . . 
        { 
          test: /\.css$/,
          loader: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['to-string-loader', 'css-loader', 'postcss-loader'],
          }),
         // NOTE: Omitting 'include' causes plugin error
          include: [helpers.root('src', 'styles')]
        },
       // . . .
      ]
```

**Comment by Sobient** [comment]
Had this issue on Node 7.2.0. Downloaded the 6.11.0 version and suddenly it worked.

**Comment by steve-todorov** [comment]
It doesn't seem to be related to the version of Node. I also had 7.2 and downgrading to 6.11 didn't solve the problem for me.

**Comment by dryqiao** [comment]
node v8.9.4,fail

**Comment by jrjacobs24** [comment]
I am experiencing this issue as well with trying to use scss. I installed it the other day and it was working. Switched branches, came back, and then it started showing up. My team is using **yarn v0.27.5**. I have installed `node-sass`, `style-loader`, `css-loader`, and `sass-loader`. Not sure what else the error could be referring to. Any help or insight is appreciated.

The relevant portion of our webpack.config is:

```
module: {
    rules: [
      // ...
      {
        test: /\.(s*)css$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        })
      },
      // ...
  },
```

Error:
```
ERROR in ./assets/scss/root.scss
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
at Object.pitch (/Users/path/to/node_modules/extract-text-webpack-plugin/dist/loader.js:57:11)
```
(the path above was updated to `path/to` for redaction purposes)

**Comment by Jonarod** [comment]
@jrjacobs24 did you finally get it to work somehow? I have the same issue happening...

**Comment by jrjacobs24** [comment]
@Jonarod I'm sorry, man but I honestly can't remember how I got it working. Somehow I did and just kept plowing ahead because I was so excited haha This was also about a month ago. I'm pretty sure I attempted some uninstalling and reinstalling. FWIW here's what my final setup looked like:

```js
module: {
    rules: [
      // ...
      {
        test: /\.(s*)css$/,
          exclude: /node_modules/,
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: {
                  minimize: false,
                  sourceMap: true,
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  sourceMap: true,
                  config: { ctx: { env } }
                }
              },
              {
                loader: 'sass-loader',
                options: {
                  sourceMap: true,
                  outFile: 'scss/build/',
                  outputStyle: 'expanded',
                  precision: 20
                },
              }
            ],
          })
      },
      // ...
  },
// ...
plugins: [
      // Output our compiled Scss to a stylesheet
      new ExtractTextPlugin({
        filename: 'scss/build/styles.css',
        allChunks: true
      })
],
```

**Comment by Jonarod** [comment]
@jrjacobs24 Aaaaah.Got it working thanks !!!!! I doubled-checked my webpack config and thought it was already coming with the `plugins` part... except it wasn't. Adding the `plugins:[...]` bit lead me to success !! Thanks again :)

**Comment by jrjacobs24** [comment]
@Jonarod That's awesome, man! Almost didn't include that part, but I'm glad I did!

**Comment by ohhoney1** [comment]
have this problem too.  I solve it by add option `exclude: /node_modules/`. cause load .css from `node_modules` when there is a conflict 

`import Vue from 'vue'

import 'normalize/normalize.css' // causes this error

import ElementUI from 'element-ui'
import '@/styles/theme/index.css' // this way works

import '@/styles/index.scss' // this way works`
